
; This line is a comment and is ignored
; The next line starts the "header":
M48

; Units and number format:
METRIC,LZ

; The "drill" is defined with diameter of 5.4 mm
; drill rate of 300 mm/minute and 55000 RPM.
T1C5.50

; drill rate of 300 mm/minute and 55000 RPM.
; T1C5.50F300S90


; End of header, M95 or %, and beginning of body:
M95

; Use tool 1 defined in the header
T1

; Drill Points
X007.62Y007.62
X007.62Y083.82
X132.08Y007.62
X132.08Y083.82


; End of program;
M30